name: RaceChooser
main: xfury\races\MainClass
description: Choose your ethnicity!
version: 1.0.0
author: XFuryMCPE
api: [1.13.0, 2.0.0]

commands:
 race:
  description: Choose your race!
  permission: races.use

permissions:
 races.use:
  description: Permission for /race
  default: true